[tool.briefcase]
project_name = "mygame"
bundle = "com.owais.mygame"
version = "0.0.1"
url = "https://mygame.owais.com/mygame"
license.file = "LICENSE"
author = "Jane Developer"
author_email = "jane@mygame.owais.com"

[tool.briefcase.app.mygame]
formal_name = "mygame"
description = "My first application"
long_description = """More details about the app should go here."""
sources = ["src/mygame"]

requires = [
    "pygame-ce",
]

[tool.briefcase.app.mygame.macOS]
universal_build = true
requires = ["toga-cocoa~=0.5.0", "std-nslog~=1.0.3"]

[tool.briefcase.app.mygame.linux]
requires = ["toga-gtk~=0.5.0", "pygobject < 3.52.1"]

[tool.briefcase.app.mygame.windows]
requires = ["toga-winforms~=0.5.0"]

[tool.briefcase.app.mygame.android]
requires = [
    "pygame-ce",
]
base_theme = "Theme.MaterialComponents.Light.DarkActionBar"
build_gradle_dependencies = ["com.google.android.material:material:1.13.0"]

[tool.briefcase.app.mygame.web]
requires = ["toga-web~=0.5.0"]


